---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvpn
spec:
  selector:
    matchLabels:
      app: openvpn
  template:
    metadata:
      labels:
        app: openvpn
    spec:
      {{- if .Values.openvpn.nodeSelector }}
      nodeSelector:
      {{- .Values.openvpn.nodeSelector | toYaml | indent 8 | printf "\n%s" }}
      {{- end }}
      {{- if .Values.openvpn.tolerations }}
      tolerations:
      {{- .Values.openvpn.tolerations | toYaml | indent 8 | printf "\n%s" }}
      {{- end }}
      terminationGracePeriodSeconds: 0
      containers:
      - name: openvpn
        image: ixdx/openvpn-oidc:latest
        # imagePullPolicy: Always
        env:
        - name: OPENVPN_SUBNET
          value: {{ .Values.openvpn.subnet }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - MKNOD
            - SETGID
            - SETUID
            drop:
            - ALL
        ports:
        - name: openvpn-tcp
          protocol: TCP
          containerPort: 1194
          {{- if eq .Values.openvpn.inlet "HostPort" }}
          hostPort: {{ .Values.openvpn.hostPort }}
          {{- end }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: dev-net
          mountPath: /dev/net
        - name: dexclient
          mountPath: /openvpn/oauth2
          readOnly: true
        - name: certificates-and-keys
          mountPath: /openvpn/certificates-and-keys
          readOnly: true
        - name: configs
          mountPath: /openvpn/server.conf
          subPath: server.conf
          readOnly: true
        - name: configs
          mountPath: /openvpn/oidc-config.yaml
          subPath: oidc-config.yaml
          readOnly: true
      volumes:
      - name: tmp
        emptyDir: {}
      - name: dev-net
        emptyDir: {}
      - name: dexclient
        secret:
          secretName: dex-client-dexclient
          items:
          - key: clientSecret
            path: clientSecret
      - name: certificates-and-keys
        secret:
          secretName: certificates-and-keys
          items:
          - key: ca
            path: ca.crt
          - key: cert
            path: server.crt
          - key: key
            path: server.key
          - key: dh
            path: dh.pem
          - key: tls
            path: ta.key
      - name: configs
        configMap:
          name: configs
