---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: certificates-and-keys
data:
  ca: {{ .Values.openvpn.secret.ca | b64enc }}
  cert: {{ .Values.openvpn.secret.cert | b64enc }}
  key: {{ .Values.openvpn.secret.key | b64enc }}
  dh: {{ .Values.openvpn.secret.dh | b64enc }}
  tls: {{ .Values.openvpn.secret.tls | b64enc }}
